Complete the OpenSearch 1.3 cutover in the main tree.
Merge the shipped server and build to the Cassandra 4.0 plus OpenSearch 1.3 baseline, carry over the wave-4 runtime fixes, and align CI and release metadata with the new line.

diff --git a/distribution/packages/src/common/scripts/postinst b/distribution/packages/src/common/scripts/postinst
--- a/distribution/packages/src/common/scripts/postinst
+++ b/distribution/packages/src/common/scripts/postinst
@@ -8,17 +8,12 @@
 #       $1=0         : indicates a removal
 #       $1=1         : indicates an upgrade
 
-
-
-# Sets the default values for cassandra variables used in this script
-CASSANDRA_USER="cassandra"
-CASSANDRA_GROUP="cassandra"
-
-# Source the default env file
-ES_ENV_FILE="${path.env}"
-if [ -f "$ES_ENV_FILE" ]; then
-    . "$ES_ENV_FILE"
+# source the default env file
+if [ -f "${path.env}" ]; then
+    . "${path.env}"
 fi
+
+export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-${path.conf}}
 
 IS_UPGRADE=false
 
@@ -31,18 +26,22 @@ case "$1" in
         if [ -n $2 ]; then
             IS_UPGRADE=true
         fi
+        PACKAGE=deb
     ;;
     abort-upgrade|abort-remove|abort-deconfigure)
+        PACKAGE=deb
     ;;
 
     # RedHat ####################################################
     1)
         # If $1=1 this is an install
         IS_UPGRADE=false
+        PACKAGE=rpm
     ;;
     2)
         # If $1=1 this is an upgrade
         IS_UPGRADE=true
+        PACKAGE=rpm
     ;;
 
     *)
@@ -51,62 +50,71 @@ case "$1" in
     ;;
 esac
 
-# to pick up /usr/lib/sysctl.d/cassandra.conf
+# to pick up /usr/lib/sysctl.d/opensearch.conf
 if command -v systemctl > /dev/null; then
-    systemctl restart systemd-sysctl.service
+    systemctl restart systemd-sysctl.service || true
 fi
 
 if [ "x$IS_UPGRADE" != "xtrue" ]; then
     if command -v systemctl >/dev/null; then
-        echo "### NOT starting on installation, please execute the following statements to configure cassandra service to start automatically using systemd"
+        echo "### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using systemd"
         echo " sudo systemctl daemon-reload"
-        echo " sudo systemctl enable cassandra.service"
-        echo "### You can start cassandra service by executing"
-        echo " sudo systemctl start cassandra.service"
+        echo " sudo systemctl enable opensearch.service"
+        echo "### You can start opensearch service by executing"
+        echo " sudo systemctl start opensearch.service"
 
     elif command -v chkconfig >/dev/null; then
-        echo "### NOT starting on installation, please execute the following statements to configure cassandra service to start automatically using chkconfig"
-        echo " sudo chkconfig --add cassandra"
-        echo "### You can start cassandra service by executing"
-        echo " sudo service cassandra start"
+        echo "### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using chkconfig"
+        echo " sudo chkconfig --add opensearch"
+        echo "### You can start opensearch service by executing"
+        echo " sudo service opensearch start"
 
     elif command -v update-rc.d >/dev/null; then
-        echo "### NOT starting on installation, please execute the following statements to configure cassandra service to start automatically using chkconfig"
-        echo " sudo update-rc.d cassandra defaults 95 10"
-        echo "### You can start cassandra service by executing"
-        echo " sudo /etc/init.d/cassandra start"
+        echo "### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using chkconfig"
+        echo " sudo update-rc.d opensearch defaults 95 10"
+        echo "### You can start opensearch service by executing"
+        echo " sudo /etc/init.d/opensearch start"
     fi
 elif [ "$RESTART_ON_UPGRADE" = "true" ]; then
 
-    echo -n "Restarting cassandra service..."
+    echo -n "Restarting opensearch service..."
     if command -v systemctl >/dev/null; then
         systemctl daemon-reload
-        systemctl restart cassandra.service || true
+        systemctl restart opensearch.service || true
 
-    elif [ -x /etc/init.d/cassandra ]; then
+    elif [ -x /etc/init.d/opensearch ]; then
         if command -v invoke-rc.d >/dev/null; then
-            invoke-rc.d cassandra stop || true
-            invoke-rc.d cassandra start || true
+            invoke-rc.d opensearch stop || true
+            invoke-rc.d opensearch start || true
         else
-            /etc/init.d/cassandra restart || true
+            /etc/init.d/opensearch restart || true
         fi
 
     # older suse linux distributions do not ship with systemd
     # but do not have an /etc/init.d/ directory
-    # this tries to start the cassandra service on these
+    # this tries to start the opensearch service on these
     # as well without failing this script
-    elif [ -x /etc/rc.d/init.d/cassandra ] ; then
-        /etc/rc.d/init.d/cassandra restart || true
+    elif [ -x /etc/rc.d/init.d/opensearch ] ; then
+        /etc/rc.d/init.d/opensearch restart || true
     fi
     echo " OK"
 fi
 
-chown -R $CASSANDRA_USER:$CASSANDRA_GROUP /var/lib/cassandra
-chown -R $CASSANDRA_USER:$CASSANDRA_GROUP /var/log/cassandra
-chown -R root:$CASSANDRA_GROUP /etc/cassandra
-chmod 0755 /etc/cassandra
-chmod 0750 /etc/cassandra/triggers
-chmod 0750 /etc/cassandra/scripts
-chmod 0664 "${path.env}"
+# the equivalent code for rpm is in posttrans
+if [ "$PACKAGE" = "deb" ]; then
+    if [ ! -f "${OPENSEARCH_PATH_CONF}"/opensearch.keystore ]; then
+        /usr/share/opensearch/bin/opensearch-keystore create
+        chown root:opensearch "${OPENSEARCH_PATH_CONF}"/opensearch.keystore
+        chmod 660 "${OPENSEARCH_PATH_CONF}"/opensearch.keystore
+        md5sum "${OPENSEARCH_PATH_CONF}"/opensearch.keystore > "${OPENSEARCH_PATH_CONF}"/.opensearch.keystore.initial_md5sum
+    else
+        if /usr/share/opensearch/bin/opensearch-keystore has-passwd --silent ; then
+          echo "### Warning: unable to upgrade encrypted keystore" 1>&2
+          echo " Please run opensearch-keystore upgrade and enter password" 1>&2
+        else
+          /usr/share/opensearch/bin/opensearch-keystore upgrade
+        fi
+    fi
+fi
 
 ${scripts.footer}
diff --git a/distribution/packages/src/common/scripts/posttrans b/distribution/packages/src/common/scripts/posttrans
--- a/distribution/packages/src/common/scripts/posttrans
+++ b/distribution/packages/src/common/scripts/posttrans
@@ -1,10 +1,22 @@
-if [ ! -f /etc/elasticsearch/elasticsearch.keystore ]; then
-    /usr/share/elasticsearch/bin/elasticsearch-keystore create
-    chown root:elasticsearch /etc/elasticsearch/elasticsearch.keystore
-    chmod 660 /etc/elasticsearch/elasticsearch.keystore
-    md5sum /etc/elasticsearch/elasticsearch.keystore > /etc/elasticsearch/.elasticsearch.keystore.initial_md5sum
+# source the default env file
+if [ -f "${path.env}" ]; then
+    . "${path.env}"
+fi
+
+export OPENSEARCH_PATH_CONF=${OPENSEARCH_PATH_CONF:-${path.conf}}
+
+if [ ! -f "${OPENSEARCH_PATH_CONF}"/opensearch.keystore ]; then
+    /usr/share/opensearch/bin/opensearch-keystore create
+    chown root:opensearch "${OPENSEARCH_PATH_CONF}"/opensearch.keystore
+    chmod 660 "${OPENSEARCH_PATH_CONF}"/opensearch.keystore
+    md5sum "${OPENSEARCH_PATH_CONF}"/opensearch.keystore > "${OPENSEARCH_PATH_CONF}"/.opensearch.keystore.initial_md5sum
 else
-    /usr/share/elasticsearch/bin/elasticsearch-keystore upgrade
+    if /usr/share/opensearch/bin/opensearch-keystore has-passwd --silent ; then
+      echo "### Warning: unable to upgrade encrypted keystore" 1>&2
+      echo " Please run opensearch-keystore upgrade and enter password" 1>&2
+    else
+      /usr/share/opensearch/bin/opensearch-keystore upgrade
+    fi
 fi
 
 ${scripts.footer}
